// src/components/footer/index.tsx
import React, { useState } from "react";

import "./styles.css";

const Footer = () => {
  const [year] = useState<number>(new Date().getFullYear());

  return (
    <footer>
      <div className="container">
        <div className="row">
          <div className="col-12 py-2 text-center">
            <p className="mb-0 text-light font-weight-lighter">
              © Copyright {year} Wesley Belizario
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/app/components/footer/footer.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  year: number;

  constructor() {
    this.year = new Date().getFullYear();
  }

  ngOnInit(): void {
  }

}

<footer>
  <div class="container">
    <div class="row">
      <div class="col-12 py-2 text-center">
        <p class="mb-0 text-white font-weight-lighter">© Copyright {{year}} Wesley Belizario</p>
      </div>
    </div>
  </div>
</footer>
