// src/components/gallery/index.tsx
import React, { useState } from "react";

import "./styles.css";
import imageOne from "./../../images/gallery/1.jpg";
import imageTwo from "./../../images/gallery/2.jpg";
import imageTree from "./../../images/gallery/3.jpg";
import Card from "./card";

interface Image {
  title: string;
  path: string;
  spotifyLink: string;
}

const Gallery = () => {
  const [images] = useState<Image[]>([
    {
      title: "Sem medo - Mahmundi",
      path: imageOne,
      spotifyLink:
        "https://open.spotify.com/track/31YDFOH4f9fOhF0CGWEFds?si=mHevpPPWSv-Ikz989EH7sA",
    },
    {
      title: "King - Years & Years",
      path: imageTwo,
      spotifyLink:
        "https://open.spotify.com/track/3AeicLnm55RqcXGBKYQolM?si=-X6e11REQ-OhXjTTMv--iQ",
    },
    {
      title: "Lights - Ellie Goulding",
      path: imageTree,
      spotifyLink:
        "https://open.spotify.com/track/5aTsxlQlq0vIedDWZoqMWN?si=LBUJxJRoRgiwehXtG4tfaw",
    },
  ]);

  return (
    <div id="galeria">
      <div className="gallery-blankspace"></div>
      <section className="my-5">
        <div className="container">
          <div className="row">
            <div className="col">
              <h1 className="text-light text-center">Galeria</h1>
            </div>
          </div>
        </div>
        <div className="container-box">
          {images.map((image: Image, index: number) => {
            return (
              <Card
                key={index}
                title={image.title}
                path={image.path}
                spotifyLink={image.spotifyLink}
              />
            );
          })}
        </div>
      </section>
    </div>
  );
};

export default Gallery;

// src/app/components/gallery/gallery.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss']
})
export class GalleryComponent implements OnInit {

  images = [
    {
      title: 'Sem medo - Mahmundi',
      path: './assets/img/gallery/1.jpg',
      spotifyMusic: 'https://open.spotify.com/track/31YDFOH4f9fOhF0CGWEFds?si=mHevpPPWSv-Ikz989EH7sA'
    },
    {
      title: 'Lights - Ellie Goulding',
      path: './assets/img/gallery/2.jpg',
      spotifyMusic: 'https://open.spotify.com/track/5aTsxlQlq0vIedDWZoqMWN?si=LBUJxJRoRgiwehXtG4tfaw'
    },
    {
      title: 'King - Years & Years',
      path: './assets/img/gallery/3.jpg',
      spotifyMusic: 'https://open.spotify.com/track/3AeicLnm55RqcXGBKYQolM?si=-X6e11REQ-OhXjTTMv--iQ'
    }
  ];

  constructor() {
  }

  ngOnInit(): void {
  }

}

<div style="height: 40vh" id="galeria"></div>

<section class="my-5">

  <div class="row">
    <div class="col-md-12" data-aos="fade-up" data-aos-duration="1500">
      <h1 class="text-white text-center">Galeria</h1>
    </div>
  </div>

  <div class="container d-none-lg" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="400">
    <div class="box" *ngFor="let image of images">
      <img src="{{image.path}}" alt="{{image.title}}">
      <span><a href="{{image.spotifyMusic}}" target="_blank" rel="noopener">♫ {{image.title}}</a></span>
    </div>
  </div>

  <div class="container text-center d-visible">
    <div class="row">
      <div class="col-12 mb-4" *ngFor="let image of images">
        <div class="box" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="400">
          <img src="{{image.path}}" class="img-fluid" width="500" alt="{{image.title}}">
          <span><a href="{{image.spotifyMusic}}" rel="noopener">♫ {{image.title}}</a></span>
        </div>
      </div>
    </div>
  </div>

</section>

<div class="h-after-photos"></div>
