// src/app/components/contact/contact.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent implements OnInit {

  contacts = [
    {
      link: 'https://www.instagram.com/wesleyxbz',
      path: './assets/icon/instagram.svg',
      alt: 'instagram'
    },
    {
      link: 'https://github.com/WesleyxBZ',
      path: './assets/icon/github.svg',
      alt: 'github'
    },
    {
      link: 'https://www.linkedin.com/in/wesley-belizario-824127162/',
      path: './assets/icon/linkedIn.svg',
      alt: 'linkedIn'
    },
    {
      link: 'https://steamcommunity.com/id/wesleyxbz',
      path: './assets/icon/steam.svg',
      alt: 'steam'
    }
  ];

  constructor() {
  }

  ngOnInit(): void {
  }

}

<section id="contato" data-aos="fade-up" data-aos-duration="1500">
  <div class="container-fluid d-flex justify-content-center">
    <div class="align-self-center">
      <div class="row">
        <div class="col-md-12">
          <a *ngFor="let contact of contacts" href="{{contact.link}}" target="_blank" rel="noopener">
            <img src="{{contact.path}}" class="img-fluid" alt="{{contact.alt}}">
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

// src/components/contact/index.tsx
import React, { useState } from "react";

import "./styles.css";
import iconLinkedin from "./../../images/icon-linkedin.svg";
import iconInstagram from "./../../images/icon-instagram.svg";
import iconGithub from "./../../images/icon-github.svg";

interface Social {
  src: string;
  alt: string;
  href: string;
}

const Contact = () => {
  const [socials] = useState<Social[]>([
    {
      src: iconLinkedin,
      alt: "",
      href: "https://www.linkedin.com/in/wesley-belizario-824127162",
    },
    {
      src: iconGithub,
      alt: "",
      href: "https://github.com/WesleyxBZ",
    },
    {
      src: iconInstagram,
      alt: "",
      href: "https://www.instagram.com/wesleyxbz",
    },
  ]);

  return (
    <section id="contato">
      <div className="d-flex justify-content-center contact">
        <div className="align-self-center">
          <div className="row">
            <div className="col">
              {socials.map((social: Social, index: number) => {
                return (
                  <a
                    key={index}
                    className="mx-4 "
                    href={social.href}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <img
                      className="img-zoom"
                      src={social.src}
                      alt={social.alt}
                    />
                  </a>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Contact;
